### ISSUE TITLE
Unable to run the EXE on Windows 10

### ISSUE THREAD

**Issue by Chikimaro** [OnyxParse/SpectraX#1]
![image](https://github.com/user-attachments/assets/4c95d7f7-ace4-47e5-8526-e61a69bbb8a5)

**Comment by Chikimaro** [comment]
Tu es sûr ? L'exe fait 1 KB.

**Comment by OnyxParse** [comment]
Réinstalle l'exe, il devrait faire autour de 110 MB

**Comment by Chikimaro** [comment]
Merci, mais comme c'est une source fermée, il y a beaucoup de choses suspectes comme rlim.com, je ne peux pas prendre de risques, mais merci pour votre aide.

**Comment by OnyxParse** [comment]
Je comprends que les sources fermées peuvent sembler suspectes
En ce qui concerne rlim.com, ils sont utilisés pour la version du programme et pour notre mécanisme d'auto-déchiffrage dédié à JapScan
